sudo: false
language: shell
os:
  - windows
  - linux

cache:
  directories:
    - $HOME/.m2
#    - /c/bin

before_install:
  - if [[ $TRAVIS_OS_NAME = windows ]]; then choco install jdk8 -params 'installdir=c:\\bin\\jdk' -y; export JAVA_HOME=/c/bin/jdk; else sudo add-apt-repository ppa:openjdk-r/ppa -y; sudo apt update; sudo apt-get install -y openjdk-8-jdk; export JAVA_HOME=`which java`; fi
  - if [[ $TRAVIS_OS_NAME = windows ]]; then choco install maven --version 3.6.0 -y; else sudo apt-get install -y maven2; fi
  - echo $JAVA_HOME
  - ls -la $JAVA_HOME

before_script:
  mvn install -s settings.xml -P -jdeps -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  mvn test -s settings.xml -P -jdeps -B

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - cat /c/ProgramData/chocolatey/logs/chocolatey.log
