sudo: false
language: bash
os:
  - windows
  - linux

env:
    - MAVIS="https://raw.githubusercontent.com/nidi3/Mavis-CI/master/" JDK="adopt@1.8.212-04" MAVEN_VERSION=3.6.0
cache:
  directories:
    - $HOME/.m2
#    - /c/bin

before_install:
  - curl "${MAVIS}.install-jdk-travis.sh" --output .install-jdk-travis.sh
  - source .install-jdk-travis.sh
  - curl "${MAVIS}.install-maven-travis.sh" | source

before_script:
  mvn install -s settings.xml -P -jdeps -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  mvn test -s settings.xml -P -jdeps -B

after_success:
  - bash <(curl -s https://codecov.io/bash)
