sudo: false
language: shell
os:
  - windows
  - linux

cache:
  directories:
    - $HOME/.m2
    - /c/bin

before_install:
  - '[ -d /c/bin/jdk && "$TRAVIS_OS_NAME"="windows" ] || choco install jdk8 -params "installdir=/c/bin/jdk" -y'
  - "[ -d /c/bin/mvn ] || choco install maven -params 'installdir=/c/bin/mvn' --version 3.6.0 -y"
  - export JAVA_HOME=${JAVA_HOME:-/c/bin/jdk}
script:
  mvn install -P -jdeps

after_success:
  - bash <(curl -s https://codecov.io/bash)