sudo: false
language: bash
os:
  - windows
  - linux

env:
    - MAVIS="https://raw.githubusercontent.com/nidi3/Mavis-CI/master" JDK="adopt@1.8.212-04"
cache:
  directories:
    - $HOME/.m2
#    - /c/bin

before_install:
  - curl "${MAVIS}/mavis.sh" --output mavis.sh
  - source mavis.sh
  - install_jdk
  - install_maven

before_script:
  mvn install -P -jdeps -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  mvn test -s settings.xml -P -jdeps -B

after_success:
  - bash <(curl -s https://codecov.io/bash)
