sudo: false
language: shell
os: windows

cache:
  directories:
    - $HOME/.m2
    - $HOME/bin

before_install:
  - choco install jdk8 -params 'installdir=$HOME\\jdk' -y
  - choco install maven -params 'installdir=$HOME\\mvn' --version 3.6.0 -y
  - export JAVA_HOME=${JAVA_HOME:-$HOME/jdk}
  - echo $JAVA_HOME
script:
  mvn install