language: bash
dist: xenial
os:
  - windows
  - linux

env:
  - JDK="adopt@1.8.212-04"

cache:
  directories:
    - $HOME/.m2

before_install:
  - curl "https://raw.githubusercontent.com/nidi3/Mavis-CI/master/mavis.sh" --output mavis.sh
  - source mavis.sh
  - install_jdk
  - install_maven

before_script:
  before_script -P -jdeps

script:
  script -P -jdeps

after_success:
  - bash <(curl -s https://codecov.io/bash)
