sudo: false
language: shell
os: windows
before_install:
  - choco install jdk8 -params 'installdir=c:\\jdk' -y
  - choco install maven -params 'installdir=c:\\mvn' --version 3.6.0 -y
script:
  mvn install