sudo: false
language: shell
os: windows

cache:
  directories:
    - $HOME/.m2
    - /c/bin

before_install:
  - "[ -d /c/bin ] && echo 'e' || echo 'ne'"
  - "[ -d c:\\bin ] && echo 'e' || echo 'ne'"
  - "choco install jdk8 -params 'installdir=c:\\bin\\jdk' -y"
  - choco install maven -params 'installdir=c:\\bin\\mvn' --version 3.6.0 -y
  - export JAVA_HOME=${JAVA_HOME:-/c/bin/jdk}
script:
  mvn install -P -jdeps