sudo: false
language: shell
os:
  - windows
  - linux

cache:
  directories:
    - $HOME/.m2
#    - /c/bin

before_install:
  - "if [[ $TRAVIS_OS_NAME = windows ]]; then choco install jdk8 -params 'installdir=c:\\bin\\jdk' -y; else sudo add-apt-repository ppa:openjdk-r/ppa; sudo apt update; sudo apt-get install -y openjdk-8-jdk; fi"
  - "if [[ $TRAVIS_OS_NAME = windows ]]; then choco install maven -params 'installdir=c:\\bin\\mvn' --version 3.6.0 -y; else sudo apt-get install -y maven2; fi"
  - export JAVA_HOME=${JAVA_HOME:-/c/bin/jdk}

before_script:
  mvn install -P -jdeps -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  mvn test -B

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - cat /c/ProgramData/chocolatey/logs/chocolatey.log
