sudo: false
language: shell
os:
  - windows
  - linux

cache:
  directories:
    - $HOME/.m2
#    - /c/bin

before_install:
  - echo $TRAVIS_OS_NAME
  - "if [[ $TRAVIS_OS_NAME==windows ]]; then echo 'w'; else echo 'nw'; fi"
  - "if [[ $TRAVIS_OS_NAME==windows ]]; then choco install jdk8 -params 'installdir=/c/bin/jdk' -y; else sudo apt-get install -y jdk8; fi"
  - "if [[ $TRAVIS_OS_NAME==windows ]]; then choco install maven -params 'installdir=/c/bin/mvn' --version 3.6.0 -y; else sudo apt-get install -y maven2; fi"
  - export JAVA_HOME=${JAVA_HOME:-/c/bin/jdk}

before_script:
  mvn install -P -jdeps -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  mvn test -B

after_success:
  - bash <(curl -s https://codecov.io/bash)